FIX ME!!!!!
sbLocalDatabaseTreeView.o: In function `nsIAtom::ToString(nsAString&)':
nightingale/dependencies/linux-x86_64/mozilla-9.0.1/debug/include/nsIAtom.h:59:
    undefined reference to `nsStringBuffer::ToString(unsigned int,nsAString&, int)'

Commented out that section since it was added all together in:
ec12d952f36102b46091d89d70436250e61cf1b8

Simply commenting out the "atom->ToString(s);" line allows it to compile
though.

I can't find anything different from 1.9.2 to 9.0.1 dep wise though that
would have made this an issue?
It's only when a nsIAtom calls its "<atom>->ToString(<string>)"